POST http://localhost:5000/v1/api/user/signup
Content-Type: application/json

{
    "email":"toxic4",
    "password":"ahihi"
}

###
POST  http://localhost:5000/v1/api/user/signin
Content-Type: application/json

{
    "email":"toxic3",
    "password":"ahihi"
}
